### Check in office
POST http://localhost:3000/api/v1/my-visits/checkin
Content-Type: application/json
Accept: application/json

{
  "place": "OFFICE",
  "address": "Five Star Tower"
}

### Check-out office
POST http://localhost:3000/api/v1/my-visits/checkout
Content-Type: application/json
Accept: application/json

{
  "place": "OFFICE",
  "address": "Five Star Tower"
}

### Retrieve office visits
GET http://localhost:3000/api/v1/my-visits/office-visits